// Use: Read-only finalized audit report library for assessors.

import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { Download, Eye, FileText } from "lucide-react";
import { PageShell } from "../../components/shared/PageShell";
import { api } from "../../lib/api";

type Report = {
  report_id: string;
  report_name: string;
  report_type?: string;
  framework_name?: string;
  generated_by_name?: string;
  generated_at?: string;
};

export default function ReportLibrary() {
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);
  const [filters, setFilters] = useState({ search: "", type: "", framework: "", from: "", to: "" });

  useEffect(() => {
    async function load() {
      try {
        const { data } = await api.get<Report[]>("/api/v1/audit/reports");
        setReports(Array.isArray(data) ? data : []);
      } finally {
        setLoading(false);
      }
    }
    void load();
  }, []);

  const filtered = useMemo(() => reports.filter((report) => {
    const text = `${report.report_name} ${report.report_type ?? ""} ${report.framework_name ?? ""}`.toLowerCase();
    const generated = report.generated_at ? new Date(report.generated_at) : null;
    if (filters.search && !text.includes(filters.search.toLowerCase())) return false;
    if (filters.type && report.report_type !== filters.type) return false;
    if (filters.framework && report.framework_name !== filters.framework) return false;
    if (filters.from && generated && generated < new Date(filters.from)) return false;
    if (filters.to && generated && generated > new Date(`${filters.to}T23:59:59`)) return false;
    return true;
  }), [reports, filters]);

  const types = Array.from(new Set(reports.map((r) => r.report_type).filter(Boolean))) as string[];
  const frameworks = Array.from(new Set(reports.map((r) => r.framework_name).filter(Boolean))) as string[];

  async function download(report: Report) {
    const response = await api.get(`/api/v1/audit/reports/${report.report_id}/download`, { responseType: "blob" });
    const url = URL.createObjectURL(response.data);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `${report.report_name || "report"}.html`;
    anchor.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div style={{ display: "grid", gap: 16 }}>
      <PageShell title="Report Library" context="Finalized reports generated by Compliance and Audit teams." />

      <section className="card">
        <div className="grid-4">
          <input className="form-input" placeholder="Search reports" value={filters.search} onChange={(e) => setFilters((f) => ({ ...f, search: e.target.value }))} />
          <select className="form-input" value={filters.type} onChange={(e) => setFilters((f) => ({ ...f, type: e.target.value }))}>
            <option value="">All types</option>
            {types.map((type) => <option key={type} value={type}>{type}</option>)}
          </select>
          <select className="form-input" value={filters.framework} onChange={(e) => setFilters((f) => ({ ...f, framework: e.target.value }))}>
            <option value="">All frameworks</option>
            {frameworks.map((framework) => <option key={framework} value={framework}>{framework}</option>)}
          </select>
          <div className="flex gap-2">
            <input className="form-input" type="date" value={filters.from} onChange={(e) => setFilters((f) => ({ ...f, from: e.target.value }))} />
            <input className="form-input" type="date" value={filters.to} onChange={(e) => setFilters((f) => ({ ...f, to: e.target.value }))} />
          </div>
        </div>
      </section>

      {loading ? <section className="card">Loading reports...</section> : filtered.length === 0 ? (
        <section className="card text-center" style={{ padding: 48 }}>
          <FileText size={36} color="var(--text-secondary)" />
          <p className="mt-3">No reports available yet. Reports are generated by the Compliance Officer and Auditor.</p>
        </section>
      ) : (
        <div className="grid-3">
          {filtered.map((report) => (
            <article key={report.report_id} className="card" style={{ display: "grid", gap: 12 }}>
              <div>
                <h3 className="card-title">{report.report_name}</h3>
                <p className="text-sm text-secondary-color">{report.framework_name || "No framework"} · {report.report_type || "custom"}</p>
              </div>
              <div className="text-sm text-secondary-color">
                <div>Generated by: {report.generated_by_name || "System"}</div>
                <div>{report.generated_at ? new Date(report.generated_at).toLocaleString() : "No date"}</div>
              </div>
              <div className="flex gap-2">
                <Link className="btn btn-secondary btn-sm" to={`/assessor/reports/${report.report_id}`}><Eye size={14} /> View</Link>
                <button className="btn btn-secondary btn-sm" onClick={() => void download(report)}><Download size={14} /> Download</button>
              </div>
            </article>
          ))}
        </div>
      )}
    </div>
  );
}
